### ISSUE TITLE
Error in InOutAttendanceByDateRangeAndUser

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#201]
Request URL: https://regularlystaging.azurewebsites.net/api/InOutAttendanceByDateRangeAndUser?dateFrom=2016-11-21&dateTo=2016-11-22&UserID=568654c2-da33-4d16-8f1c-fd78faa14aad
Request Method:GET
Status Code:200 OK

Token : 

bearer yX8hK5Ys7IEAugnnZAdRz6H9NzxCEJj3qwNazx4oe67OX2368oJlpWxPoKF6TdApKTD-q5LnvxYAgiz3jxgD26oOFuEi3A0LC9ohNZ_zJQHIkYCp9r2-4zzSLZZVeEnljyq8qpnMgOo_UYhO38LuxMiLz-RH1Kt7abs7_fLLMZ38KTwRdD1Xk2YRavPqJSHpkbgXRSuR9Q3UzHKfyayI7LpALNGuqFveLN_UpxGtBKESf8WaOqVZKx0xSb1jYVJAlaPcSpahoCEb1mwhXSuM7J6Ho8sTbxiFb1J8UNEOailH7toQnMnVHY7fuNxCHhrN-b-93gVONeSoCbwwveIk3X_49x5Xyix7VZsiKm8LyMceqqh9cXVv5mwrZFWRueo0JpUWi7XKC8EqqaVq56U-YzJNxjFPYmTk5Khft3Jr3pwBSU64tTj9uvSHnmEAAoPuh20EA0K5-TH1G1k7kRuCFgLcTZuiXQHsEwfnu0jGZuPpnCHJNQQ6hmsSSjRazNv4WnlB8-FhOpMp4sXyYHrDA2lKYZM2_GNHNK97A-FEQXXq8_TVl1QwG5CmzBlnu-_ZjfDEW0HEexn9GdHskg_O6dRG5uMVKvZ8hY05VxID1ohwmRenSQHZn5fLHPYPeYwCkM-YufShDd1pvCkXouIRVBAYEY6Wh4KoNrVLj9_3KNkmMbVR9Y4K0iODPlTqop4fcqzZurJMeUffkrfcyCowbZXRZJaLR1tac03sDy6Lj62SeYCvlrQvFhlnvP7QMkgNkOtbufCwgyuLdFbaWItmSPmk8DxF_m5qd2swMLBvkvqYAsjtVWOsNiOg3iymy_5yR8vBqFkKqPYXvKqw3VjDhFmxeJOPWeuRG736SmtI2lxBnGZ3DGtwHvH1SucfifU5ixdzoRoUFHcn8DdZBBNLNtf0Z-aueBTPyvBiqgTXy0w

Query String
dateFrom:2016-11-21
dateTo:2016-11-22
UserID:568654c2-da33-4d16-8f1c-fd78faa14aad

Response: 

[{"EmpID":"568654c2-da33-4d16-8f1c-fd78faa14aad","FirstName":"jogendra","LastName":"jha","InTime":null,"OutTime":null,"Present":false,"Punctual":false,"TotalWorked":null}]

**Comment by krishnandusarkar** [comment]
As discussed with @trijitdey this has been done intentionally. Notice that I'm sending False in Present.

This has been done because... Say a company have 5 users and on a given day only 3 users are present. So if you don't get the name of 2 users who are absent how would you show who is absent on that given day?

You have to call another API to get the users of company and find distinct user from the above api and show them. 

Thus I send all the users of company in this API irrespective of they being present or absent so that you can also show who's absent (atleast the names).

Let me know if this is not the expected behavior.

**Comment by snowbreeze** [comment]
Ok this is fine. @trijit handle in client end

**Comment by moutusi12singh** [comment]
fixed.
